---
# This role deploys the mongodb processes and sets up settings.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_distribution }}.yml"

- include: "setup-{{ ansible_os_family }}.yml"
